name: Deploy to GAE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Replace EnvVariables
      uses: 73h/gae-app-yaml-replace-env-variables@v0.3
      env:
        BOOKIPLY_API_KEY: ${{ secrets.BOOKIPLY_API_KEY }}
        FA_API_KEY: ${{ secrets.FA_API_KEY }}
        Flask_Secret_Key_FEWO: ${{ secrets.FLASK_SECRET_KEY_FEWO }}
        smtp_server: ${{ secrets.SMTP_SERVER }}
        smtp_user: ${{ secrets.SMTP_USER }}
        smtp_password: ${{ secrets.SMTP_PASSWORD }}
      with:
        app_yaml_path: "app.yaml"
    - name: Authenticate with Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
          project_id: ${{ secrets.GCP_PROJECT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          id_token_audience: 'https://github.com/jonaboecker/bookiply_availability-calendar'
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v2
      with:
        deliverables: app.yaml
        project_id: ${{ secrets.GCP_PROJECT }}